### ISSUE TITLE
Manual Date/Time entry / Author entry?

### ISSUE THREAD

**Issue by Duderocktv** [xFutte/futte-newspaper#12]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Manual input of Month, Date, Year

Some servers, like mine, play in a different era. 
Could go as far as adding the ability to change Author for "Pen Names" , etc

**Describe alternatives you've considered**
I could go remove the date portion of the script but I am shit at javascript

**Additional context**
N/A

**Comment by xFutte** [comment]
To understand it correctly, do you want to display the time of a published story relative to the client's timezone?

**Comment by xFutte** [comment]
In regards to removing the date option as an alternative, I've already made an option for that in config.js

**Comment by xFutte** [comment]
@Duderocktv I've now added support for this in the config.js. Just change `customYear: undefined` to the year you want to publish in.
