### ISSUE TITLE
Unsure if it's intentional

### ISSUE THREAD

**Issue by lordfalcon22** [xFutte/futte-newspaper#16]
**What is your question?**
You have your import.sql to create table "newspaper" but your server side calls for a database table "newsstands"

**Comment by xFutte** [comment]
I renamed the resource at some point - must have missed that part. Thanks for letting me know.

**Comment by xFutte** [comment]
Solved in commit 6625913504fe987bb3dea295974122f8cd1732a3

**Comment by AscendoTuum86** [comment]
It looks like the word "newsstands" was just mass replaced to "newspaper" to solve this but now it broke the news stands... you cant actually get a newspaper.

**Comment by xFutte** [comment]
> It looks like the word "newsstands" was just mass replaced to "newspaper" to solve this but now it broke the news stands... you cant actually get a newspaper.

You're right. I've not committed the issue in commit 330e021b5db03e28bead896207aecc83669ef55e
