### ISSUE TITLE
Prison Sentence undefined

### ISSUE THREAD

**Issue by notConfiscate** [xFutte/futte-newspaper#19]
https://i.imgur.com/b5HFzSC.jpeg

Followed the readme, don't believe I skipped anything? Any chance you could tell me what i did wrong?

**Comment by xFutte** [comment]
Yeah, you are not parsing the name with the export. Remember it takes both name and months as parameters.

**Comment by notConfiscate** [comment]
https://i.imgur.com/k7FNkyr.png Just like this right? This is in my policejob/server/main

**Comment by xFutte** [comment]
Yes, almost. You are missing the name because the name you are parsing in the export actually is undefined. I've gotten this question a couple of times, so I'll add a snippet to the README in a minute.

**Comment by notConfiscate** [comment]
Thank you!!

**Comment by xFutte** [comment]
Try it out with the code in the README.md now and see if it works.

**Comment by notConfiscate** [comment]
Works perfect now, thank you!
