### ISSUE TITLE
Discord Webook for News Stories

### ISSUE THREAD

**Issue by Duderocktv** [xFutte/futte-newspaper#24]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Discord Webhook feature for posting new stories to a Discord Channel

**Describe alternatives you've considered**
Packaging it with my ad system, but having a format specific for the newspaper would be amazing

**Additional context**
Thank you for this amazing resource

**Comment by xFutte** [comment]
Not something that'll be worked on. I want the newspaper to be purely in-game to keep everything related to it IC.
