### ISSUE TITLE
Multiple Publications / News Papers

### ISSUE THREAD

**Issue by Duderocktv** [xFutte/futte-newspaper#25]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to have multiple Publications / Newspapers.

For example: Job 1 (Reporter) could edit Newspaper 1 
Job 2 (Journalist) could edit Newspaper 2

Config.Papers = {
1 =  { job = "reporter", paper = "weazelnews" },
2 = { job = "journalist", paper ="dailybugle" }
}

I hope that makes sense!

**Describe alternatives you've considered**

I can copy and paste the script and change some stuff for every instance of the news paper, but it would be a more optimized all in one package! 

**Additional context**
I love your newspaper

**Comment by xFutte** [comment]
This is not something that will be supported in short term. Maybe it will be added long-term.
