### ISSUE TITLE
Mugshots

### ISSUE THREAD

**Issue by MrNewb** [xFutte/futte-newspaper#26]
**Is your feature request related to a problem? Please describe.**
Could you add mugshots to the prison sentences?

**Describe the solution you'd like**
Could you add mugshots to the prison sentences?

**Describe alternatives you've considered**
Could you add mugshots to the prison sentences?

**Additional context**
Could you add mugshots to the prison sentences?

**Comment by xFutte** [comment]
Not something that's planned for - there are other features, I'll rather implement first. You're of course more than welcome to make a pull request with it.
