### ISSUE TITLE
Multiple Publications:

### ISSUE THREAD

**Issue by Duderocktv** [xFutte/futte-newspaper#27]
**Is your feature request related to a problem? Please describe.**
We LOVE your newspaper script - it's amaazing. But we ran into a bit of an RP issue (lol)
We have a member wanting to post a "tabloid" paper (rumours, comedy, etc) but some players feel like it discredits the 'newspaper' as an official source of neews (basically mixing the satire amongst real news)

**Describe the solution you'd like**
Offer the ability to have different Publications / Categories. So Weazel News could have one section and Daily Globe could have another. Even adding tabloids or a section for comics

**Describe alternatives you've considered**
Copy Pasting the script and changing the name of the script/events/etc

**Additional context**
To go even further, being able to assign different jobs to different categories would be amazing.
Or assign one category to one ITEM, and not have all categories available from one item (each newspaper item only opens its respective category.)

**Comment by xFutte** [comment]
The solution you provide is actually already possible. You can freely add another tab to the menu, where you list another type of news within. After that, copy/paste the database query for requesting a specific type of news, and you're good to go. Then you'll just need to add another type of "reporter menu", where the type of news that gets posted differs from the original one.

Hope it helps.
