### ISSUE TITLE
Yarn Error in Console

### ISSUE THREAD

**Issue by Ginjakz** [xFutte/futte-newspaper#28]
_Many outreaches has been about code not changing when developing. Make sure that you are compiling your code when developing. Follow the README.md_

----

**Describe the bug**
[         script:yarn] Error: [yarn] warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[         script:yarn] 
[         script:yarn] SCRIPT ERROR in timer: Error: EACCES: permission denied, open '/home/zap948299/g490632/gta5-fivem-txadmin/QBCoreFramework_44CF7E.base/resources/[scripts]/futte-newspaper/.yarn.installed'

**To Reproduce**
Followed steps in README when installing exactly

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/116679253/197865052-f0274e9f-b16f-4902-980b-96a1a7946dbe.png)

**Additional context**

**Comment by xFutte** [comment]
Good find. I guess I committed the package-lock file by accident.
