### ISSUE TITLE
Not adding prison sentence to the prison sentences 

### ISSUE THREAD

**Issue by jokernights** [xFutte/futte-newspaper#35]
Not sure if I put the export in the wrong place or not, but it is not putting the prison sentences on the tab on the newspaper. I have used /jail and sent from ps-mdt. below I will screen shot where i put it. everything else works such as publishing stories and viewing

I use Rcore-prison which i know they added the support for it now. Didn't know if i had to do something with rcore for it to work?

![image](https://github.com/user-attachments/assets/a6ef23b6-e850-4a46-b561-cdc74bc93b1b)

**Comment by xFutte** [comment]
Did you check that it gets set into your database?
