### ISSUE TITLE
When you jail someone the database only saves their ID not their name, so the news paper says "5 has been sentenced to 5 xxxxx"

### ISSUE THREAD

**Issue by tday130** [xFutte/futte-newspaper#38]
**Describe the bug**
When you jail someone it only reads the persons ID. I'd like it to read their actual name in the newspaper rather than their ID so that players can tell who was jailed, I think it would also enhance the entire feeling of the newspaper script, it would be more realistic. IRL you can find out who goes to jail by their name, the script would be perfect if it could read their name instead of the ID. Also Im having trouble changing the PNGs of the UI itself like the prison photo I tried to use the same picture but add out server logo to it, I change the link in the code but it doesn't change the picture ever.

**Comment by tday130** [comment]
![Screenshot 2024-10-01 175255](https://github.com/user-attachments/assets/d977869e-88ad-4d66-a2d7-f0bc6d1ffc43)

**Comment by tday130** [comment]
Nothing for name in the database

**Comment by tday130** [comment]
![Screenshot 2024-10-01 175408](https://github.com/user-attachments/assets/b724d003-222d-4f64-9d2c-fdfc1e8c50c1)
The newspaper itself, reading the id from the database and not a name, and saying 1 has been sentenced to 1 month. Has everyone been using this script like this ? No one uses it with names somehow?

**Comment by xFutte** [comment]
@tday130 Look in the README.md file. It says what needs to be added to policejob. If you add that, it should work out-of-the-box. This is what sets the name.
