### ISSUE TITLE
When you jail someone the database only saves their ID not their name, so the news paper says "5 has been sentenced to 5 xxxxx"

### ISSUE THREAD

**Issue by tday130** [xFutte/futte-newspaper#39]
When you jail someone it only reads the persons ID. I'd like it to read their actual name in the newspaper rather than their ID so that players can tell who was jailed, I think it would also enhance the entire feeling of the newspaper script, it would be more realistic. IRL you can find out who goes to jail by their name, the script would be perfect if it could read their name instead of the ID. Also Im having trouble changing the PNGs of the UI itself like the prison photo I tried to use the same picture but add out server logo to it, I change the link in the code but it doesn't change the picture ever. 

My last issue ticket was closed with a response that did not help, so im opening it again. I followed the read me already. I will provide screenshots

**Comment by tday130** [comment]
![Screenshot 2024-10-02 225724](https://github.com/user-attachments/assets/b6731e49-1757-4090-86a6-dff8d8317746)

**Comment by tday130** [comment]
![Screenshot 2024-10-01 175255](https://github.com/user-attachments/assets/9f2e5985-dfac-4c5f-9606-15bab779ecc5)
![Screenshot 2024-10-01 175408](https://github.com/user-attachments/assets/9edd3f57-c3cd-41cc-b59d-ac6d32527074)

**Comment by tday130** [comment]
Its not reading the name, its only recording the ID data.

**Comment by xFutte** [comment]
Please provide a screenshot of a table entry.

**Comment by tday130** [comment]
What do you mean a table entry? I provided the sql data table screenshot already (:

**Comment by xFutte** [comment]
> What do you mean a table entry? I provided the sql data table screenshot already (:

No, you provided me with the table structure, not the table with any data.

> Can you provide me a screenshot of this script working in the game to the point where the names are showing up in the newspaper and not the id? Every server using this script has to be experiencing this issue...

You are the first in the time the resource has been available who has notified me about this, so I think it is on your end.

**Comment by tday130** [comment]
![Screenshot 2024-10-06 142857](https://github.com/user-attachments/assets/1a27e889-ca50-42fb-be6c-e036f3b91a91)

**Comment by tday130** [comment]
The jailed_player is reading the players id

**Comment by tday130** [comment]
you there?

**Comment by xFutte** [comment]
Ask for support in my Discord - can be found on my profile.
